export const Countries = {
  items: [
    {StateGroupID: 0, name: 'United States', code: 'US'},
    {StateGroupID: 1, name: 'Afghanistan', code: 'AF'},
    {StateGroupID: 2, name: 'Albania', code: 'AL'},
    {StateGroupID: 3, name: 'Algeria', code: 'DZ'},
    {StateGroupID: 4, name: 'American Samoa', code: 'AS'},
    {StateGroupID: 5, name: 'Andorra', code: 'AD'},
    {StateGroupID: 6, name: 'Angola', code: 'AO'},
    {StateGroupID: 7, name: 'Anguilla', code: 'AI'},
    {StateGroupID: 8, name: 'Antigua and Barbuda', code: 'AG'},
    {StateGroupID: 9, name: 'Argentina', code: 'AR'},
    {StateGroupID: 10, name: 'Armenia', code: 'AM'},
    {StateGroupID: 11, name: 'Aruba', code: 'AW'},
    {StateGroupID: 12, name: 'Australia', code: 'AU'},
    {StateGroupID: 13, name: 'Austria', code: 'AT'},
    {StateGroupID: 14, name: 'Azerbaijan Republic', code: 'AZ'},
    {StateGroupID: 15, name: 'Bahamas', code: 'BS'},
    {StateGroupID: 16, name: 'Bahrain', code: 'BH'},
    {StateGroupID: 17, name: 'Bangladesh', code: 'BD'},
    {StateGroupID: 18, name: 'Barbados', code: 'BB'},
    {StateGroupID: 19, name: 'Belarus', code: 'BY'},
    {StateGroupID: 20, name: 'Belgium', code: 'BE'},
    {StateGroupID: 21, name: 'Belize', code: 'BZ'},
    {StateGroupID: 22, name: 'Benin', code: 'BJ'},
    {StateGroupID: 23, name: 'Bermuda', code: 'BM'},
    {StateGroupID: 24, name: 'Bhutan', code: 'BT'},
    {StateGroupID: 25, name: 'Bolivia', code: 'BO'},
    {StateGroupID: 26, name: 'Bosnia and Herzegovina', code: 'BA'},
    {StateGroupID: 27, name: 'Botswana', code: 'BW'},
    {StateGroupID: 28, name: 'Brazil', code: 'BR'},
    {StateGroupID: 29, name: 'British Virgin Islands', code: 'VG'},
    {StateGroupID: 30, name: 'Brunei Darussalam', code: 'BN'},
    {StateGroupID: 31, name: 'Bulgaria', code: 'BG'},
    {StateGroupID: 32, name: 'Burkina Faso', code: 'BF'},
    {StateGroupID: 33, name: 'Burundi', code: 'BI'},
    {StateGroupID: 34, name: 'Cambodia', code: 'KH'},
    {StateGroupID: 35, name: 'Cameroon', code: 'CM'},
    {StateGroupID: 36, name: 'Canada', code: 'CA'},
    {StateGroupID: 37, name: 'Cape Verde Islands', code: 'CV'},
    {StateGroupID: 38, name: 'Cayman Islands', code: 'KY'},
    {StateGroupID: 39, name: 'Central African Republic', code: 'CF'},
    {StateGroupID: 40, name: 'Chad', code: 'TD'},
    {StateGroupID: 41, name: 'Chile', code: 'CL'},
    {StateGroupID: 42, name: 'China', code: 'CN'},
    {StateGroupID: 43, name: 'Colombia', code: 'CO'},
    {StateGroupID: 44, name: 'Comoros', code: 'KM'},
    {StateGroupID: 45, name: 'Congo', code: 'CG'},
    {StateGroupID: 46, name: 'Congo, The Democratic Republic of the', code: 'CD'},
    {StateGroupID: 47, name: 'Cook Islands', code: 'CK'},
    {StateGroupID: 48, name: 'Costa Rica', code: 'CR'},
    {StateGroupID: 49, name: 'Cote D\'Ivoire (Ivory Coast)', code: 'CI'},
    {StateGroupID: 50, name: 'Croatia', code: 'HR'},
    {StateGroupID: 51, name: 'Cuba', code: 'CU'},
    {StateGroupID: 52, name: 'Cyprus', code: 'CY'},
    {StateGroupID: 53, name: 'Czech Republic', code: 'CZ'},
    {StateGroupID: 54, name: 'Denmark', code: 'DK'},
    {StateGroupID: 55, name: 'Djibouti', code: 'DJ'},
    {StateGroupID: 56, name: 'Dominica', code: 'DM'},
    {StateGroupID: 57, name: 'Dominican Republic', code: 'DO'},
    {StateGroupID: 58, name: 'Ecuador', code: 'EC'},
    {StateGroupID: 59, name: 'Egypt', code: 'EG'},
    {StateGroupID: 60, name: 'El Salvador', code: 'SV'},
    {StateGroupID: 61, name: 'Equatorial Guinea', code: 'GQ'},
    {StateGroupID: 62, name: 'Eritrea', code: 'ER'},
    {StateGroupID: 63, name: 'Estonia', code: 'EE'},
    {StateGroupID: 64, name: 'Ethiopia', code: 'ET'},
    {StateGroupID: 65, name: 'Falkland Islands (Malvinas)', code: 'FK'},
    {StateGroupID: 66, name: 'Fiji', code: 'FJ'},
    {StateGroupID: 67, name: 'Finland', code: 'FI'},
    {StateGroupID: 68, name: 'France', code: 'FR'},
    {StateGroupID: 69, name: 'French Guiana', code: 'GF'},
    {StateGroupID: 70, name: 'French Polynesia', code: 'PF'},
    {StateGroupID: 71, name: 'Gabon Republic', code: 'GA'},
    {StateGroupID: 72, name: 'Gambia', code: 'GM'},
    {StateGroupID: 73, name: 'Georgia', code: 'GE'},
    {StateGroupID: 74, name: 'Germany', code: 'DE'},
    {StateGroupID: 75, name: 'Ghana', code: 'GH'},
    {StateGroupID: 76, name: 'Gibraltar', code: 'GI'},
    {StateGroupID: 77, name: 'Greece', code: 'GR'},
    {StateGroupID: 78, name: 'Greenland', code: 'GL'},
    {StateGroupID: 79, name: 'Grenada', code: 'GD'},
    {StateGroupID: 80, name: 'Guadeloupe', code: 'GP'},
    {StateGroupID: 81, name: 'Guam', code: 'GU'},
    {StateGroupID: 82, name: 'Guatemala', code: 'GT'},
    {StateGroupID: 83, name: 'Guernsey', code: 'GG'},
    {StateGroupID: 84, name: 'Guinea', code: 'GN'},
    {StateGroupID: 85, name: 'Guinea-Bissau', code: 'GW'},
    {StateGroupID: 86, name: 'Guyana', code: 'GY'},
    {StateGroupID: 87, name: 'Haiti', code: 'HT'},
    {StateGroupID: 88, name: 'Honduras', code: 'HN'},
    {StateGroupID: 89, name: 'Hungary', code: 'HU'},
    {StateGroupID: 90, name: 'Iceland', code: 'IS'},
    {StateGroupID: 91, name: 'India', code: 'IN'},
    {StateGroupID: 92, name: 'Indonesia', code: 'ID'},
    {StateGroupID: 93, name: 'Ireland', code: 'IE'},
    {StateGroupID: 94, name: 'Israel', code: 'IL'},
    {StateGroupID: 95, name: 'Italy', code: 'IT'},
    {StateGroupID: 96, name: 'Jamaica', code: 'JM'},
    {StateGroupID: 97, name: 'Japan', code: 'JP'},
    {StateGroupID: 98, name: 'Jersey', code: 'JE'},
    {StateGroupID: 99, name: 'Jordan', code: 'JO'},
    {StateGroupID: 100, name: 'Kazakhstan', code: 'KZ'},
    {StateGroupID: 101, name: 'Kenya', code: 'KE'},
    {StateGroupID: 102, name: 'Kiribati', code: 'KI'},
    {StateGroupID: 103, name: 'Korea, South', code: 'KW'},
    {StateGroupID: 104, name: 'Kuwait', code: 'KW'},
    {StateGroupID: 105, name: 'Kyrgyzstan', code: 'KG'},
    {StateGroupID: 106, name: 'Laos', code: 'LA'},
    {StateGroupID: 107, name: 'Latvia', code: 'LV'},
    {StateGroupID: 108, name: 'Lebanon', code: 'LB'},
    {StateGroupID: 109, name: 'Liechtenstein', code: 'LI'},
    {StateGroupID: 110, name: 'Lithuania', code: 'LT'},
    {StateGroupID: 111, name: 'Luxembourg', code: 'LU'},
    {StateGroupID: 112, name: 'Macao', code: 'MO'},
    {StateGroupID: 113, name: 'Macedonia', code: 'MK'},
    {StateGroupID: 114, name: 'Madagascar', code: 'MG'},
    {StateGroupID: 115, name: 'Malawi', code: 'MW'},
    {StateGroupID: 116, name: 'Malaysia', code: 'MY'},
    {StateGroupID: 117, name: 'Maldives', code: 'MV'},
    {StateGroupID: 118, name: 'Mali', code: 'ML'},
    {StateGroupID: 119, name: 'Malta', code: 'MT'},
    {StateGroupID: 120, name: 'Marshall Islands', code: 'MH'},
    {StateGroupID: 121, name: 'Martinique', code: 'MQ'},
    {StateGroupID: 122, name: 'Mauritania', code: 'MR'},
    {StateGroupID: 123, name: 'Mauritius', code: 'MU'},
    {StateGroupID: 124, name: 'Mayotte', code: 'YT'},
    {StateGroupID: 125, name: 'Mexico', code: 'MX'},
    {StateGroupID: 126, name: 'Micronesia', code: 'FM'},
    {StateGroupID: 127, name: 'Moldova', code: 'MD'},
    {StateGroupID: 128, name: 'Monaco', code: 'MC'},
    {StateGroupID: 129, name: 'Mongolia', code: 'MN'},
    {StateGroupID: 130, name: 'Montserrat', code: 'MS'},
    {StateGroupID: 131, name: 'Morocco', code: 'MA'},
    {StateGroupID: 132, name: 'Mozambique', code: 'MZ'},
    {StateGroupID: 133, name: 'Myanmar', code: 'MM'},
    {StateGroupID: 134, name: 'Namibia', code: 'NA'},
    {StateGroupID: 135, name: 'Nauru', code: 'NR'},
    {StateGroupID: 136, name: 'Nepal', code: 'NP'},
    {StateGroupID: 137, name: 'Netherlands', code: 'NL'},
    {StateGroupID: 138, name: 'Netherlands Antilles', code: 'AN'},
    {StateGroupID: 139, name: 'New Caledonia', code: 'NC'},
    {StateGroupID: 140, name: 'New Zealand', code: 'NZ'},
    {StateGroupID: 141, name: 'Nicaragua', code: 'NI'},
    {StateGroupID: 142, name: 'Niger', code: 'NE'},
    {StateGroupID: 143, name: 'Nigeria', code: 'NG'},
    {StateGroupID: 144, name: 'Niue', code: 'NU'},
    {StateGroupID: 145, name: 'Norway', code: 'NO'},
    {StateGroupID: 146, name: 'Oman', code: 'OM'},
    {StateGroupID: 147, name: 'Pakistan', code: 'PK'},
    {StateGroupID: 148, name: 'Palau', code: 'PW'},
    {StateGroupID: 149, name: 'Panama', code: 'PA'},
    {StateGroupID: 150, name: 'Papua New Guinea', code: 'PG'},
    {StateGroupID: 151, name: 'Paraguay', code: 'PY'},
    {StateGroupID: 152, name: 'Peru', code: 'PE'},
    {StateGroupID: 153, name: 'Philippines', code: 'PH'},
    {StateGroupID: 154, name: 'Poland', code: 'PL'},
    {StateGroupID: 155, name: 'Portugal', code: 'PT'},
    {StateGroupID: 156, name: 'Puerto Rico', code: 'PR'},
    {StateGroupID: 157, name: 'Qatar', code: 'QA'},
    {StateGroupID: 158, name: 'Reunion', code: 'RE'},
    {StateGroupID: 159, name: 'Romania', code: 'RO'},
    {StateGroupID: 160, name: 'Russian Federation', code: 'RU'},
    {StateGroupID: 161, name: 'Rwanda', code: 'RW'},
    {StateGroupID: 162, name: 'Saint Helena', code: 'SH'},
    {StateGroupID: 163, name: 'Saint Kitts and Nevis', code: 'KN'},
    {StateGroupID: 164, name: 'Saint Lucia', code: 'LC'},
    {StateGroupID: 165, name: 'Saint Pierre and Miquelon', code: 'PM'},
    {StateGroupID: 166, name: 'Saint Vincent and the Grenadines', code: 'VC'},
    {StateGroupID: 167, name: 'Samoa', code: 'WS'},
    {StateGroupID: 168, name: 'San Marino', code: 'SM'},
    {StateGroupID: 169, name: 'Saudi Arabia', code: 'SA'},
    {StateGroupID: 170, name: 'Senegal', code: 'SN'},
    {StateGroupID: 171, name: 'Serbia and Montenegro', code: 'CS'},
    {StateGroupID: 172, name: 'Seychelles', code: 'SC'},
    {StateGroupID: 173, name: 'Sierra Leone', code: 'SL'},
    {StateGroupID: 174, name: 'Singapore', code: 'SG'},
    {StateGroupID: 175, name: 'Slovakia', code: 'SK'},
    {StateGroupID: 176, name: 'Slovenia', code: 'SI'},
    {StateGroupID: 177, name: 'Solomon Islands', code: 'SB'},
    {StateGroupID: 178, name: 'Somalia', code: 'SO'},
    {StateGroupID: 179, name: 'South Africa', code: 'ZA'},
    {StateGroupID: 180, name: 'Spain', code: 'ES'},
    {StateGroupID: 181, name: 'Sri Lanka', code: 'LK'},
    {StateGroupID: 182, name: 'Sudan', code: 'SD'},
    {StateGroupID: 183, name: 'Suriname', code: 'SR'},
    {StateGroupID: 184, name: 'Svalbard', code: 'SJ'},
    {StateGroupID: 185, name: 'Swaziland', code: 'SZ'},
    {StateGroupID: 186, name: 'Sweden', code: 'SE'},
    {StateGroupID: 187, name: 'Switzerland', code: 'CH'},
    {StateGroupID: 188, name: 'Tahiti'},
    {StateGroupID: 189, name: 'Taiwan', code: 'TW'},
    {StateGroupID: 190, name: 'Tajikistan', code: 'TJ'},
    {StateGroupID: 191, name: 'Tanzania, United Republic of', code: 'TZ'},
    {StateGroupID: 192, name: 'Thailand', code: 'TH'},
    {StateGroupID: 193, name: 'Togo', code: 'TG'},
    {StateGroupID: 194, name: 'Tonga', code: 'TO'},
    {StateGroupID: 195, name: 'Trinidad and Tobago', code: 'TT'},
    {StateGroupID: 196, name: 'Tunisia', code: 'TN'},
    {StateGroupID: 197, name: 'Turkey', code: 'TR'},
    {StateGroupID: 198, name: 'Turkmenistan', code: 'TM'},
    {StateGroupID: 199, name: 'Turks and Caicos Islands', code: 'TC'},
    {StateGroupID: 200, name: 'Tuvalu', code: 'TV'},
    {StateGroupID: 201, name: 'Uganda', code: 'UG'},
    {StateGroupID: 202, name: 'Ukraine', code: 'UA'},
    {StateGroupID: 203, name: 'United Arab Emirates', code: 'AE'},
    {StateGroupID: 204, name: 'United Kingdom', code: 'GB'},
    {StateGroupID: 205, name: 'Uruguay', code: 'UY'},
    {StateGroupID: 206, name: 'Uzbekistan', code: 'UZ'},
    {StateGroupID: 207, name: 'Vanuatu', code: 'VU'},
    {StateGroupID: 208, name: 'Venezuela', code: 'VE'},
    {StateGroupID: 209, name: 'Vietnam', code: 'VN'},
    {StateGroupID: 210, name: 'Virgin Islands, U.S.', code: 'VI'},
    {StateGroupID: 211, name: 'Wallis and Futuna', code: 'WF'},
    {StateGroupID: 212, name: 'Western Sahara', code: 'EH'},
    {StateGroupID: 213, name: 'Yemen', code: 'YE'},
    {StateGroupID: 214, name: 'Zambia', code: 'ZM'},
    {StateGroupID: 215, name: 'Zimbabwe', code: 'ZW'}
  ]
};
